### ISSUE TITLE
camera settings: orthographic

### ISSUE THREAD

**Issue by elija-feigl** [sulcgroup/oxdna-viewer#16]
request: 
orthographic camera mode

reason:
translations in a perspective camera deviate strongly from the human expectation in three dimensions. especially far away from the center. 
for rearranging and aligning larger structures changing to an orthographic camera would be extremely helpful.

**Comment by ErikPoppleton** [comment]
I've pushed a quick version of this, when you hit the "Orthographic" button in the sidebar it now switches the camera type.  The camera swap will always cause a bit of a jump because of the difference in how the camera displays scenes, however the orthographic camera currently always starts in the hemisphere centered on the default camera position.  It also does not properly handle window resizes.  I will fix these before closing this issue.

If you have not yet, I suggest taking a look at the keyboard shortcuts, the numpad shortcuts should help with setting the camera for editing.

**Comment by ErikPoppleton** [comment]
The orthographic camera is finished.  Sorry it took a bit, there was an issue with the way it interacted with dragControls getting the wrong camera position for calculating where to move objects to.  Let me know if anything still behaves weirdly.

**Comment by mckwxp** [comment]
It seems that I cannot zoom in orthographic mode...
