### ISSUE TITLE
Exported seqeunces appear to be backwards

### ISSUE THREAD

**Issue by bensonbits** [sulcgroup/oxdna-viewer#18]
3' to 5' instead of 5' to 3' 

Cheers

Erik

**Comment by ErikPoppleton** [comment]
Hi Erik,

They appear fine to me.  Are you working with a sequence you edited in oxView?  Since oxDNA stores sequences 3'-5', but most users will have things written 5'-3', we decided that all I/O to oxView would be 5'-3'.  If you tried to be smarter than the app and pre-flipped the sequences to be 3'-5' to match oxDNA, oxView will flip them back and you will end up with inverted sequences (this has happened to me before).

Cheers,

Erik

**Comment by bensonbits** [comment]
Hi Erik, 

There is something strange going on, previously the visual arrows where pointing in the wrong direction, ie not 5' to 3' but i think this was fixed. Now i made a tiny "origami" in cadano with a long 3' extension and converted it in tacoxdna, and looked at it in oxview. I can see the long protrusion but it appears to be going in the wrong direction according to the arrows. 

Cheers

Erik

**Comment by bensonbits** [comment]
Ok, so it seems like the sequence export is actually correct and corresponds with cadnano, but the graphical arrows are pointing in the wrong direction. 

Sorry for the confusion. 

Cheers 
Erik

**Comment by ErikPoppleton** [comment]
Could you send me the files (slack is a good way) so I can take a look?

**Comment by bensonbits** [comment]
Done!
