### ISSUE TITLE
Structures with different box sizes 

### ISSUE THREAD

**Issue by bensonbits** [sulcgroup/oxdna-viewer#21]
Hi guys!

I pulled in two different origami that have different box sizes. If i pull in the smaller box origami second, it will force the larger origami into the smaller box, causing weird effects. Pulling the small box origami first works well. I think it would be better to keep the largest box when merging multiple structures. 

Cheers

Erik B

**Comment by ErikPoppleton** [comment]
@Akodiat Can you take a look at this?  I would also argue that the PBC and centering should be applied on a per-system basis instead of everything moving to maintain centering when a new structure is added to the scene.

**Comment by Akodiat** [comment]
Keeping the largest box should be fairly simple to do.
Do you mean each system having its own box and origin? That sounds a bit more tricky and I'm not sure how much it would help. Perhaps just not apply centring and PBC automatically when additional systems are added?

**Comment by ErikPoppleton** [comment]
If I remember, the way it worked before you implemented the better in-boxing algorithm was that each system would be centered off its own points when first loaded.  Right now everything jumps when you add a new system to the scene because the inboxing is calculated off everything.  This is not always intuitive because its based off the new system's pre-boxing/centering positions.

I'll send you an example file.

**Comment by Akodiat** [comment]
Thank you for the files, it should not jump anymore now
