### ISSUE TITLE
How to switch off PBC while making movie?

### ISSUE THREAD

**Issue by prateek-neuronets** [sulcgroup/oxdna-viewer#67]
Greetings,

Just wanted to know how we can turn off the periodic boundary conditions when making a movie. For instance, in GROMACS we can do this in post-processing. Is there anyway to accomplish this using oxView such that the structure is seen as a whole and not split between the edges of the simulation box?

Thanking you,
Prateek

**Comment by ErikPoppleton** [comment]
Hi Prateek,

If your structure is going through the periodic boundary as visualized in oxView, your simulation box is probably too small and there is a chance you are seeing non-physical artifacts from the structure interacting with itself.  When you turn on the box in the View tab of oxView, what do you see (feel free to attach a screenshot)?  The "Fix Diffusion" function in oxDNA has a habit of shifting random parts of the structure over by 1 box length, so it is not feasible to view oxDNA simulations without applying PBC.  If you want to try anyway, before you load the structure, go to the View tab of oxView and set "Centering" and "PBC" to "None" and then load the structure as normal.

**Comment by prateek-neuronets** [comment]
Hi Erik,

I had kept the simulation box small in an effort to promote better interactions (not using VMMC & order parameters) resulting in the formation of dimers (highlighted in pink). I am seeing that my 3 way junctions are hybridizing with each other when viewed with PBC centered to 'strand'  (picture attached) whereas no interaction is being shown to occur when PBC is set to 'None' (picture attached). Centering is set to none in both cases and the snaps are taken at the same instance in the simulation. Why would this be? 

<img width="959" alt="PBC_strand" src="https://user-images.githubusercontent.com/73783939/141961123-0a590bd7-4c21-4b9b-b865-56809acefecc.png">

<img width="959" alt="PBC_none" src="https://user-images.githubusercontent.com/73783939/141961075-cc2c3422-9a4b-410a-8d36-9a58e2129dd4.png">



Best wishes,
Prateek

**Comment by ErikPoppleton** [comment]
Hi Prateek,

This is what I mentioned about the simulation engine randomly shifting entire strands over by one box.  Remember that the boxes are periodic, so strands are still interacting even if they're in different boxes, which is why it is important to apply periodic boundary conditions when analyzing simulation results.

Looking at the inboxed image, your box is almost certainly too small and you could have structures that form across the boundary, which is an extremely non-physical result unless you very carefully set up a crystal lattice with a barostat which keeps the structure stable over the boundary.
