### ISSUE TITLE
Incompatibility between .dat and .top files when viewing the trajectory

### ISSUE THREAD

**Issue by prateek-neuronets** [sulcgroup/oxdna-viewer#68]
Good day!

When I load the trajectory along with the corresponding topology file on oxView, the full trajectory is not shown; only certain configurations are shown and pop ups appear on the top right saying that .dat and .top files are incompatible. The last conf and the topology are compatible just the trajectory and the topology aren't. This particular issue is happening after I carry out MC relaxation of my structure (whose trajectory runs fine) and use its last configuration as the initial for my next step of relaxation. 

Please help me in this matter. Thank you for your time and consideration. Pardon me if this is the wrong place to post the query. 

Warm Regards
Prateek

**Comment by m-matthies** [comment]
Hi @Prateek1410, nice to see you are using our tools. 
Can you please provide a sample file where this is occurring ? 
Another thing you might check, if you do a 
`wc - l trajectory.dat` the number you get should be dividable by the number of lines of your last-conf   `wc -l last_conf.dat`,
if it is not you most likely have a corrupted trajectory file. (yet another check is that the number of lines in the configuration file should be 3+ the number of particles in your topology file)

**Comment by prateek-neuronets** [comment]
Hi Michael,

I tried those commands but it shows no output so ultimately I had to abort it. Yes, the number of files in my initial configuration are 3+ the number of particles in my topology.  I am trying to upload my files using .zip but it says, "is not included in the list". Is there another way to share the files?

I'm enjoying using oxDNA; it has been a great tool as a newbie to the field of simulation. Many thanks!

Warm Regards
Prateek

**Comment by zoombya** [comment]
[tetDimerRelaxed.zip](https://github.com/sulcgroup/oxdna-viewer/files/7610269/tetDimerRelaxed.zip)

**Comment by m-matthies** [comment]
Hi Prateek, not sure what you are doing as I can upload a zip file just fine.
There might be a size limit thought.  You could use Google Drive / Dropbox to share smth larger.
But it would still help if you compress the files first.
On the commands showing no output.
Are you running them in a linux shell, in the directory where your files are located? And do you change the name of the files to match your names ? 
**wc** is a build in linux tool so it simply can't give you no "it shows no output"

**Comment by prateek-neuronets** [comment]
Hi Michael,

[Here's](https://drive.google.com/drive/folders/1HyiVNS0Za6-DGNdlLVBu2VQDvZIyfmjB?usp=sharing) the drive link; there are 2 folders: one contains my structure while the other contains the files for the VMMC tutorial by Will Kaufhold [here](https://github.com/WillTKaufhold1/oxdna-tutorial) that I have been going through off late. In both the folders I have kept other simulation relevant files in case they are of any help. 

For my structure, I ran an MD relaxation of 1e5 steps after having run an MC relaxation of 5000 steps earlier. Regarding the wc command, sorry I had made a silly error; the lines in trajectory are not dividable by those in last conf (3288606/16424). 

In Kaufhold's tutorial folder, there are two trajectories: one that was originally there (trajectory.dat) and one that I obtained after running the simulation myself (mytrajectory.dat). My trajectory shows the incompatibility error whereas the original one doesn't. Comparing the two, it seems there are some errors in the way my trajectory is written—every configuration barring the first doesn't start in a new line but is clumped with the last line of the previous configuration. Moreover, the box size and energy information are repeated.

I'm using the latest version of oxDNA on HPC clusters; since GPU is unavailable all my runs are on CPU. 

Thanks a lot for your help. Have a good day!

Warm Regards
Prateek

**Comment by m-matthies** [comment]
Hi Prateek, you have a very interesting structure.
The problem with your files is that you most likely had 2 processes of oxDNA running at the same time.
I also took the liberty and ran a relaxation of it. These types of structures require a rather large box, 
and running rigid body relaxation is also recommended if you want to speed up the relaxation by a lot.
Another problem to look out for is that the dynamics of the system is highly sequence dependent.
If you want to infer any usable data - make sure your sequences match the actual origami design.
 
[HTBRelaxed.zip](https://github.com/sulcgroup/oxdna-viewer/files/7621062/HTBRelaxed.zip)

**Comment by prateek-neuronets** [comment]
Hi Michael,

By two process you mean we can't run two simulations simultaneously? I wasn't aware about that. Interestingly, yesterday, this hinge simulation that I shared with you ran fine on my PC with all the parameters being the same albeit I had decreased the number of steps to 1e4 from 1e5. So, I am still confused as to what is causing the problem. I wondered if it could be a faulty installation of the oxDNA on the HPC but then, I have had simulations of the hinge that have run just fine on it before. 

How do I use the oxView files you have shared? They don't run on oxView. Pardon me but what are they? How can I determine the required size of the box? Did the relaxation run well? Thanks for the valuable suggestions. I'll look into the those. Thanks a lot for your assistance. 

Warm Regards
Prateek

**Comment by m-matthies** [comment]
- By two processes I mean that you had two oxDNA processes running on the same input file in the same folder.
This would mean that both of them were writing to the file **HTB_PostMCRelax_0.5M_2_trajectory.dat** in your case.
This happens if you are not careful. And would mean if this happens to your production simulation that you would need to redo the run as the trajectory is broken irreparably. 
- The oxView files are the native format of **oxView**, they save additional information like strand coloring, forces and clustering. You can open them by just drag-dropping *a single one* of them into oxView. Last time we checked they also ran from the command line interface - so I'm very surprised that you can't open them, which version of oxView are you using? 
The default most updated one is [oxview.org](https://sulcgroup.github.io/oxdna-viewer/).
But oxView files being the native format of oxView are not the native format of oxDNA so before running the simulation you would need to save them as *.dat *.top first. This you can do after loading one of these files and pressing the 
![image](https://user-images.githubusercontent.com/1756978/144086234-ad55598d-b7d2-4c97-9211-1686bc08dadd.png)
icon in the *File* menu.
- On the relaxation and box size. After running the [Rigid body dynamics](https://www.youtube.com/watch?v=ywRcV0c9zFk) the resulting structure was touching itself through the box boundaries - so I just increased the box size manually in the file.
This is done automatically  when you export oxDNA files from oxView. To do so for the oxView files you need to use the scripting interface of the browser typing the following command `box.set(<new size>,<new size>,<new size>);`.
I highly recommend watching the tutorials we provide [oxDNA Tutorials](https://www.youtube.com/channel/UC4ClrQ8xMypSbDZG2QCehpA) as well as reading the [oxView article ](https://academic.oup.com/nar/article/48/12/e72/5843822).

Please tell if you are still having problems with the oxView files as well in case everything works ;)
Kind Regards,
 
Michael Matthies

**Comment by prateek-neuronets** [comment]
Hi Michael,

Thank you, I can view the oxView files now. Just to confirm, you first did RBD relaxation of the structure then ran an MD relaxation on it, right? 

Okay, sorry, I had misunderstood what you meant by 'two oxDNA processes'. But all my runs have their own separate folder. Indeed, a few of these folders do share the same name for the input file (generic ones like, "input_relax.txt") but since we run each simulation in its own unique folder, that shouldn't pose any problem, right? Regardless, yesterday, I ran another run of the HTB_PostMCRelax_0.5M on the HPC while no other oxDNA job was running and yet the resultant trajectory showed the incompatibility error. 

Big thanks and warm regards,
Prateek

**Comment by m-matthies** [comment]
Hi Prateek, 
- on the relaxation, yes i first manually assigned 3 clusters, the top, the bridge and the bottom part of the structure and than did the RBD. Than i did a short MC run to make sure there are no overlaps between bases and than switched to MD.
All was done using oxServe, with ***Mutual Traps*** between bases with a stiffness of **3**. I'm not sure you have used the Dynamics tab yet, but we provide a 1080 Ti Graphic card on the [nanobase.org  ](https://nanobase.org) server for relaxation purposes. It is available as on oxServe backend in the Dynamics->Connect menu. 
- If you have separate folders for each run you should be fine with using the same names. 
- On your reoccurring problem. It's a dumb thing to ask but have you deleted the faulty trajectory before you resubmitted the job? As otherwise you would only continue to write to a corrupted trajectory (depending on your input file settings) Also please double check your slurm script in case you start somehow 2 oxDNA processes. 
- Another thing sometimes happening on HPC is that processes get ***sometimes*** interrupted in mid run, so your final conf might not be written completely.  
-  The incompatibility error in general means that your trajectory is somehow broken. So you can try to do the **wc** exercise or **grep t trajectory.dat** or just open up the trajectory in an editor and look what's wrong with your file. Should this problem persist with other files you might get more answers on the [oxDNA support forum](https://sourceforge.net/p/oxdna/discussion/general/) as its ***most likely*** not an issue of the viewer.

**Comment by prateek-neuronets** [comment]
Hi Michael,

1. Thanks a lot for the helpful response about the relaxation simulations. I haven't used oxServe as yet so I don't follow fully but I am sure I'd get it once I get around to using it.

2. Yes, I have separate folders for each run.

3. No, I ran the latest run in a different folder as I do with every new simulation. It's still in queue though. I'm not sure what slurm script is, Michael. Is it the .sh file we use when submitting a job on Linux? 

4.& 5. For many of my erroneous runs, I can actually view the last configuration on oxView. It's just the trajectory which shows the error which I think it reflected in its erroneous formatting: every configuration barring the first doesn't start in a new line but is clumped with the last line of the previous configuration. Moreover, the box size and energy information are repeated. Actually yes, I too, now, think that it's got nothing to do with oxView per se. Thanks for you help, Michael; it's been instrumental in traversing through this issue. I shall post on the oxDNA forum. 

Best wishes,
Prateek
