### ISSUE TITLE
Editing capabilities

### ISSUE THREAD

**Issue by zoombya** [sulcgroup/oxdna-viewer#8]
- [x] Improve placement code: Rotation | Moving
goal to utilize similar behavior like https://threejs.org/editor/
- [x] Undo stack.
- [x] Experimental CRUD on the strand objects.

**Comment by ErikPoppleton** [comment]
Because instancing creates constant-sized arrays, editing requires a quite convoluted system of creation of temporary systems to store instances while still placing new particles within the monomer-strand-system hierarchy.  The general flow I used to implement editing features is the following:

If the edit requires creation of new particles or moving particles from one system to another, a new system is created and stored in the tmpSystems array.  This system can be accessed through the basicElement.dummySys property.  This system stores the instance arrays for the new particles, but is not the grandparent of the particles.  The new basicElement is placed at the proper point in the monomer-strand-system hierarchy.  Before outputting a file, the output needs to be cleaned up using the cleanOutput() function of the API, which reads the monomer-strand-system hierarchy and rebuilds the instancing arrays and elements array from scratch to create a contiguous ordering of global ids and strand ids.  If this is not done, gaps in ids will crash oxDNA.

**Comment by ErikPoppleton** [comment]
For now, I'm closing this issue.  If at a later point somebody would like to implement the three.js/editor-like moving/rotation, they are welcome to re-open the issue.

**Comment by Akodiat** [comment]
Improved placement code is added on /dev, using threejs transformation controls: https://github.com/sulcgroup/oxdna-viewer/commit/c6432e4b
