### ISSUE TITLE
Feature request: Make it possible to highlight "unpaired" nucleotides

### ISSUE THREAD

**Issue by thenlevy** [sulcgroup/oxdna-viewer#84]
When preparing an input for oxDNA, the first steps of the relaxation operation may break some base pairs. Running the relaxation in oxView a little longer with external forces between base pairs may repair them.

It is however not very easy to see if there are "broken" base pairs in a given configuration. 
It would be nice to be able to quickly see if there are external forces involving nucleotide that are far apart, for example by highlighting these nucleotide in a special color. This would allow to quickly detect if a configuration can be given as an input for oxDNA or if it should be relaxed for a little longer

**Comment by m-matthies** [comment]
Hi, thanks for the feedback. 
The issue is to compute the bonds efficiently this has to be done in an ox-serve like way.
(as the base pair search in oxView does not account for any oxDNA logic)
Will see if i can get to it any time soon.
You can however hack yourself a script together, based on a combination of the basepairing search and the paired property 
of the bases. 
(if you get to it, i would be happy to add this as a temporary way to check these things)

**Comment by thenlevy** [comment]
When I run a base pair search before doing any relaxation, it correctly identifies all the base pairs in my design so the idea that I had in mind was to use the list of external forces (computed before the relaxation) to determine the pairs of nucleotide which are meant to be paired and to highlight those that are more that a certain distance apart. 

I could indeed write a python script that takes as input the set of external forces and the configuration file and outputs the "broken" base pair. I'll do that tomorrow

**Comment by m-matthies** [comment]
I would suggest to stick to the js api. As you would have a script file which you can just drag and drop onto oxview and highlight the features you had in mind. But if you are willing to go to python. 
The correct way to see if smth is base-paired is to use  https://lorenzo-rovigatti.github.io/oxDNA/oat/cli.html#bond-analysis
Might be the script you have in mind.

**Comment by ErikPoppleton** [comment]
As @zoombya mentioned, the correct way to do this is to use `bond_analysis` from `oat`.  If you feed it the list of bonds you want to see and a single configuration, it will give you an oxView overlay file with a binary map of 1 where the bonds are formed and 0 where they are not.

Alternatively, if you just want to see which nucleotides are paired and which are not, you can use the HB output from `oat output_bonds -v` [https://lorenzo-rovigatti.github.io/oxDNA/oat/cli.html#output-bonds](https://lorenzo-rovigatti.github.io/oxDNA/oat/cli.html#output-bonds), which will show you the hydrogen bonding energy associated with each nucleotide in the simulation.

These are both better than using oxView's built-in bond checker because they use the actual oxDNA force field, rather than a rough distance/orientation check.

EDIT: Just realized this is an ancient discussion that Micha just closed.  Still, might be useful information for somebody so I'll leave it up.
